export const Posts = [
    {
      id: 1,
      desc: "Enjoying the beautiful weather today!",
      photo: "/components/image/post_1.jpeg",
      date: "2 hours ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "/components/image/post_2.jpeg",
      date: "3 hours ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Exploring new places and making memories.",
      photo: "/components/image/post_3.jpeg",
      date: "1 day ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "/components/image/post_4.jpeg",
      date: "2 days ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "/components/image/post_5.jpeg",
      date: "3 days ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "/components/image/post_6.jpeg",
      date: "4 days ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Cherishing the moments that matter the most.",
      photo: "/components/image/post_7.jpeg",
      date: "5 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "/components/image/post_8.jpeg",
      date: "6 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Embracing the journey of self-discovery.",
      photo: "/components/image/post_9.jpeg",
      date: "1 week ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "/components/image/post_10.jpeg",
      date: "2 weeks ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];

  
  export const Users = [
    {
      id: 1,
      profilePicture: "/components/image/person_1.jpeg",
      username: "John Doe",
    },
    {
      id: 2,
      profilePicture: "/components/image/person_2.jpeg",
      username: "Jane Smith",
    },
    {
      id: 3,
      profilePicture: "/components/image/person_3.jpeg",
      username: "Alex Johnson",
    },
    {
      id: 4,
      profilePicture: "/components/image/person_4.jpeg",
      username: "Dora Wilson",
    },
    {
      id: 5,
      profilePicture: "/components/image/person_5.jpeg",
      username: "Thomas Brown",
    },
    {
      id: 6,
      profilePicture: "/components/image/person_6.jpeg",
      username: "Shirley Davis",
    },
    {
      id: 7,
      profilePicture: "/components/image/person_7.jpeg",
      username: "Travis Miller",
    },
    {
      id: 8,
      profilePicture: "/components/image/person_8.jpeg",
      username: "Kristen Garcia",
    },
    {
      id: 9,
      profilePicture: "/components/image/person_9.jpeg",
      username: "Gary Carter",
    },
    {
      id: 10,
      profilePicture: "/components/image/person_10.jpeg",
      username: "Emily Adams",
    },
  ];